---
version: 3
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: []

additional_build_steps:
  prepend_galaxy:
    - RUN pip install --upgrade ansible-core ansible-runner

images:
  base_image:
    name: quay.io/ansible/awx-ee:latest
